# Generated by Django 4.1.7 on 2023-03-20 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=30, verbose_name='User Name:')),
                ('userEmail', models.EmailField(max_length=254, unique=True, verbose_name='User Email:')),
                ('userPhone', models.CharField(max_length=30, verbose_name='User Phone:')),
                ('userRewiew', models.TextField(verbose_name='User Rewiew: ')),
            ],
        ),
    ]
